### ISSUE TITLE
[question/request] Is there a way to load data that is related to a single patient_id?

### ISSUE THREAD

**Issue by MathildaSu** [esoreq/dcarte#11]
It seems like right now I can only load the whole dataset related to a single domain.

Is there a way to specify a signle patient_id while loading the dataset?

**Comment by esoreq** [comment]
Is this due to memory problems?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ting Su ***@***.***>
Sent: Thursday, July 28, 2022 6:15:08 PM
To: esoreq/dcarte ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [esoreq/dcarte] [question/request] Is there a way to load data that is related to a single patient_id? (Issue #11)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



It seems like right now I can only load the whole dataset related to a single domain.

Is there a way to specify a signle patient_id while loading the dataset?

**Comment by MathildaSu** [comment]
No, there's currently no memory problem.

I'm building an adaptive questionnaire and an API framework that queries the dcarte to get the patient data in real-time (which will be sent to the chatbot). it's just easier if I can get patient data directly rather than filter out the user by id (which is easy enough admittedly). 

Just curious if there's already such functionality.

**Comment by esoreq** [comment]
Then just do
pid = <user random uid>
df = dcarte.load(‘dataset’,’domain’).query(‘patient_id == @pid’)

From: Ting Su ***@***.***>
Date: Thursday, 28 July 2022 at 18:56
To: esoreq/dcarte ***@***.***>
Cc: Soreq, Eyal ***@***.***>, Comment ***@***.***>
Subject: Re: [esoreq/dcarte] [question/request] Is there a way to load data that is related to a single patient_id? (Issue #11)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



No, there's currently no memory problem.

I'm building an adaptive questionnaire and an API framework that queries the dcarte to get the patient data in real-time (which will be sent to the chatbot). it's just easier if I can get patient data directly rather than filter out the user by id (which is easy enough admittedly).

Just curious if there's already such functionality.

**Comment by MathildaSu** [comment]
ok i will query. thanks.
